apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: healy-cert
spec:
  secretName: healy-tls
  dnsNames:
  - preyaswi.online
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
