apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: preyaswi/admin-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
            - name: PORT
              value: ":8888"
            - name: DOCTOR_SVC
              value: "doctor-srv:8888"
            - name: PATIENT_SVC
              value: "patient-srv:8888"

---
apiVersion: v1
kind: Service
metadata:
  name: admin-srv
spec:
  selector:
    app: admin
  ports:
    - name: admin
      protocol: TCP
      port: 8888
      targetPort: 8888