apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor
  template:
    metadata:
      labels:
        app: doctor
    spec:
      containers:
        - name: doctor
          image: preyaswi/doctor-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: doctor-srv
spec:
  selector:
    app: doctor
  ports:
    - name: doctor
      protocol: TCP
      port: 8888
      targetPort: 8888