// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: pkg/pb/doctor.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Doctor_DoctorSignUp_FullMethodName           = "/doctor.Doctor/DoctorSignUp"
	Doctor_DoctorLogin_FullMethodName            = "/doctor.Doctor/DoctorLogin"
	Doctor_DoctorsDetail_FullMethodName          = "/doctor.Doctor/DoctorsDetail"
	Doctor_IndividualDoctor_FullMethodName       = "/doctor.Doctor/IndividualDoctor"
	Doctor_DoctorProfile_FullMethodName          = "/doctor.Doctor/DoctorProfile"
	Doctor_RateDoctor_FullMethodName             = "/doctor.Doctor/RateDoctor"
	Doctor_UpdateDoctorProifle_FullMethodName    = "/doctor.Doctor/UpdateDoctorProifle"
	Doctor_Checkdoctor_FullMethodName            = "/doctor.Doctor/Checkdoctor"
	Doctor_DoctorDetailforBooking_FullMethodName = "/doctor.Doctor/DoctorDetailforBooking"
)

// DoctorClient is the client API for Doctor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DoctorClient interface {
	DoctorSignUp(ctx context.Context, in *DoctorSignUpRequest, opts ...grpc.CallOption) (*DoctorSignUpResponse, error)
	DoctorLogin(ctx context.Context, in *DoctorLoginRequest, opts ...grpc.CallOption) (*DoctorLoginResponse, error)
	DoctorsDetail(ctx context.Context, in *Doreq, opts ...grpc.CallOption) (*DoctorsDetailre, error)
	IndividualDoctor(ctx context.Context, in *Doid, opts ...grpc.CallOption) (*DoctorsDetailr, error)
	DoctorProfile(ctx context.Context, in *DoId, opts ...grpc.CallOption) (*DoctorsDetailr, error)
	RateDoctor(ctx context.Context, in *RateDoctorReq, opts ...grpc.CallOption) (*Rate, error)
	UpdateDoctorProifle(ctx context.Context, in *UpdateReq, opts ...grpc.CallOption) (*UpdateDoctor, error)
	Checkdoctor(ctx context.Context, in *Doctorreq, opts ...grpc.CallOption) (*Doctorres, error)
	DoctorDetailforBooking(ctx context.Context, in *Doctorreq, opts ...grpc.CallOption) (*Bookingres, error)
}

type doctorClient struct {
	cc grpc.ClientConnInterface
}

func NewDoctorClient(cc grpc.ClientConnInterface) DoctorClient {
	return &doctorClient{cc}
}

func (c *doctorClient) DoctorSignUp(ctx context.Context, in *DoctorSignUpRequest, opts ...grpc.CallOption) (*DoctorSignUpResponse, error) {
	out := new(DoctorSignUpResponse)
	err := c.cc.Invoke(ctx, Doctor_DoctorSignUp_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doctorClient) DoctorLogin(ctx context.Context, in *DoctorLoginRequest, opts ...grpc.CallOption) (*DoctorLoginResponse, error) {
	out := new(DoctorLoginResponse)
	err := c.cc.Invoke(ctx, Doctor_DoctorLogin_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doctorClient) DoctorsDetail(ctx context.Context, in *Doreq, opts ...grpc.CallOption) (*DoctorsDetailre, error) {
	out := new(DoctorsDetailre)
	err := c.cc.Invoke(ctx, Doctor_DoctorsDetail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doctorClient) IndividualDoctor(ctx context.Context, in *Doid, opts ...grpc.CallOption) (*DoctorsDetailr, error) {
	out := new(DoctorsDetailr)
	err := c.cc.Invoke(ctx, Doctor_IndividualDoctor_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doctorClient) DoctorProfile(ctx context.Context, in *DoId, opts ...grpc.CallOption) (*DoctorsDetailr, error) {
	out := new(DoctorsDetailr)
	err := c.cc.Invoke(ctx, Doctor_DoctorProfile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doctorClient) RateDoctor(ctx context.Context, in *RateDoctorReq, opts ...grpc.CallOption) (*Rate, error) {
	out := new(Rate)
	err := c.cc.Invoke(ctx, Doctor_RateDoctor_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doctorClient) UpdateDoctorProifle(ctx context.Context, in *UpdateReq, opts ...grpc.CallOption) (*UpdateDoctor, error) {
	out := new(UpdateDoctor)
	err := c.cc.Invoke(ctx, Doctor_UpdateDoctorProifle_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doctorClient) Checkdoctor(ctx context.Context, in *Doctorreq, opts ...grpc.CallOption) (*Doctorres, error) {
	out := new(Doctorres)
	err := c.cc.Invoke(ctx, Doctor_Checkdoctor_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doctorClient) DoctorDetailforBooking(ctx context.Context, in *Doctorreq, opts ...grpc.CallOption) (*Bookingres, error) {
	out := new(Bookingres)
	err := c.cc.Invoke(ctx, Doctor_DoctorDetailforBooking_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DoctorServer is the server API for Doctor service.
// All implementations must embed UnimplementedDoctorServer
// for forward compatibility
type DoctorServer interface {
	DoctorSignUp(context.Context, *DoctorSignUpRequest) (*DoctorSignUpResponse, error)
	DoctorLogin(context.Context, *DoctorLoginRequest) (*DoctorLoginResponse, error)
	DoctorsDetail(context.Context, *Doreq) (*DoctorsDetailre, error)
	IndividualDoctor(context.Context, *Doid) (*DoctorsDetailr, error)
	DoctorProfile(context.Context, *DoId) (*DoctorsDetailr, error)
	RateDoctor(context.Context, *RateDoctorReq) (*Rate, error)
	UpdateDoctorProifle(context.Context, *UpdateReq) (*UpdateDoctor, error)
	Checkdoctor(context.Context, *Doctorreq) (*Doctorres, error)
	DoctorDetailforBooking(context.Context, *Doctorreq) (*Bookingres, error)
	mustEmbedUnimplementedDoctorServer()
}

// UnimplementedDoctorServer must be embedded to have forward compatible implementations.
type UnimplementedDoctorServer struct {
}

func (UnimplementedDoctorServer) DoctorSignUp(context.Context, *DoctorSignUpRequest) (*DoctorSignUpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoctorSignUp not implemented")
}
func (UnimplementedDoctorServer) DoctorLogin(context.Context, *DoctorLoginRequest) (*DoctorLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoctorLogin not implemented")
}
func (UnimplementedDoctorServer) DoctorsDetail(context.Context, *Doreq) (*DoctorsDetailre, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoctorsDetail not implemented")
}
func (UnimplementedDoctorServer) IndividualDoctor(context.Context, *Doid) (*DoctorsDetailr, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IndividualDoctor not implemented")
}
func (UnimplementedDoctorServer) DoctorProfile(context.Context, *DoId) (*DoctorsDetailr, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoctorProfile not implemented")
}
func (UnimplementedDoctorServer) RateDoctor(context.Context, *RateDoctorReq) (*Rate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RateDoctor not implemented")
}
func (UnimplementedDoctorServer) UpdateDoctorProifle(context.Context, *UpdateReq) (*UpdateDoctor, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDoctorProifle not implemented")
}
func (UnimplementedDoctorServer) Checkdoctor(context.Context, *Doctorreq) (*Doctorres, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Checkdoctor not implemented")
}
func (UnimplementedDoctorServer) DoctorDetailforBooking(context.Context, *Doctorreq) (*Bookingres, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoctorDetailforBooking not implemented")
}
func (UnimplementedDoctorServer) mustEmbedUnimplementedDoctorServer() {}

// UnsafeDoctorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DoctorServer will
// result in compilation errors.
type UnsafeDoctorServer interface {
	mustEmbedUnimplementedDoctorServer()
}

func RegisterDoctorServer(s grpc.ServiceRegistrar, srv DoctorServer) {
	s.RegisterService(&Doctor_ServiceDesc, srv)
}

func _Doctor_DoctorSignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoctorSignUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorServer).DoctorSignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Doctor_DoctorSignUp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorServer).DoctorSignUp(ctx, req.(*DoctorSignUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Doctor_DoctorLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoctorLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorServer).DoctorLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Doctor_DoctorLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorServer).DoctorLogin(ctx, req.(*DoctorLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Doctor_DoctorsDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Doreq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorServer).DoctorsDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Doctor_DoctorsDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorServer).DoctorsDetail(ctx, req.(*Doreq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Doctor_IndividualDoctor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Doid)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorServer).IndividualDoctor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Doctor_IndividualDoctor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorServer).IndividualDoctor(ctx, req.(*Doid))
	}
	return interceptor(ctx, in, info, handler)
}

func _Doctor_DoctorProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorServer).DoctorProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Doctor_DoctorProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorServer).DoctorProfile(ctx, req.(*DoId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Doctor_RateDoctor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RateDoctorReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorServer).RateDoctor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Doctor_RateDoctor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorServer).RateDoctor(ctx, req.(*RateDoctorReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Doctor_UpdateDoctorProifle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorServer).UpdateDoctorProifle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Doctor_UpdateDoctorProifle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorServer).UpdateDoctorProifle(ctx, req.(*UpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Doctor_Checkdoctor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Doctorreq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorServer).Checkdoctor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Doctor_Checkdoctor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorServer).Checkdoctor(ctx, req.(*Doctorreq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Doctor_DoctorDetailforBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Doctorreq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorServer).DoctorDetailforBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Doctor_DoctorDetailforBooking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorServer).DoctorDetailforBooking(ctx, req.(*Doctorreq))
	}
	return interceptor(ctx, in, info, handler)
}

// Doctor_ServiceDesc is the grpc.ServiceDesc for Doctor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Doctor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "doctor.Doctor",
	HandlerType: (*DoctorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoctorSignUp",
			Handler:    _Doctor_DoctorSignUp_Handler,
		},
		{
			MethodName: "DoctorLogin",
			Handler:    _Doctor_DoctorLogin_Handler,
		},
		{
			MethodName: "DoctorsDetail",
			Handler:    _Doctor_DoctorsDetail_Handler,
		},
		{
			MethodName: "IndividualDoctor",
			Handler:    _Doctor_IndividualDoctor_Handler,
		},
		{
			MethodName: "DoctorProfile",
			Handler:    _Doctor_DoctorProfile_Handler,
		},
		{
			MethodName: "RateDoctor",
			Handler:    _Doctor_RateDoctor_Handler,
		},
		{
			MethodName: "UpdateDoctorProifle",
			Handler:    _Doctor_UpdateDoctorProifle_Handler,
		},
		{
			MethodName: "Checkdoctor",
			Handler:    _Doctor_Checkdoctor_Handler,
		},
		{
			MethodName: "DoctorDetailforBooking",
			Handler:    _Doctor_DoctorDetailforBooking_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/pb/doctor.proto",
}
