// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: pkg/pb/doctor.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DoctorSignUpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FullName          string `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email             string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber       string `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Password          string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	ConfirmPassword   string `protobuf:"bytes,5,opt,name=confirm_password,json=confirmPassword,proto3" json:"confirm_password,omitempty"`
	Specialization    string `protobuf:"bytes,6,opt,name=specialization,proto3" json:"specialization,omitempty"`
	YearsOfExperience int32  `protobuf:"varint,7,opt,name=years_of_experience,json=yearsOfExperience,proto3" json:"years_of_experience,omitempty"`
	LicenseNumber     string `protobuf:"bytes,8,opt,name=license_number,json=licenseNumber,proto3" json:"license_number,omitempty"`
	Fees              int64  `protobuf:"varint,9,opt,name=fees,proto3" json:"fees,omitempty"`
}

func (x *DoctorSignUpRequest) Reset() {
	*x = DoctorSignUpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_doctor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoctorSignUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorSignUpRequest) ProtoMessage() {}

func (x *DoctorSignUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_doctor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorSignUpRequest.ProtoReflect.Descriptor instead.
func (*DoctorSignUpRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_doctor_proto_rawDescGZIP(), []int{0}
}

func (x *DoctorSignUpRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *DoctorSignUpRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *DoctorSignUpRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *DoctorSignUpRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *DoctorSignUpRequest) GetConfirmPassword() string {
	if x != nil {
		return x.ConfirmPassword
	}
	return ""
}

func (x *DoctorSignUpRequest) GetSpecialization() string {
	if x != nil {
		return x.Specialization
	}
	return ""
}

func (x *DoctorSignUpRequest) GetYearsOfExperience() int32 {
	if x != nil {
		return x.YearsOfExperience
	}
	return 0
}

func (x *DoctorSignUpRequest) GetLicenseNumber() string {
	if x != nil {
		return x.LicenseNumber
	}
	return ""
}

func (x *DoctorSignUpRequest) GetFees() int64 {
	if x != nil {
		return x.Fees
	}
	return 0
}

type DoctorDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName          string `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email             string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber       string `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Specialization    string `protobuf:"bytes,5,opt,name=specialization,proto3" json:"specialization,omitempty"`
	YearsOfExperience int32  `protobuf:"varint,6,opt,name=years_of_experience,json=yearsOfExperience,proto3" json:"years_of_experience,omitempty"`
	LicenseNumber     string `protobuf:"bytes,7,opt,name=license_number,json=licenseNumber,proto3" json:"license_number,omitempty"`
	Fees              int64  `protobuf:"varint,8,opt,name=fees,proto3" json:"fees,omitempty"`
}

func (x *DoctorDetail) Reset() {
	*x = DoctorDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_doctor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoctorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorDetail) ProtoMessage() {}

func (x *DoctorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_doctor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorDetail.ProtoReflect.Descriptor instead.
func (*DoctorDetail) Descriptor() ([]byte, []int) {
	return file_pkg_pb_doctor_proto_rawDescGZIP(), []int{1}
}

func (x *DoctorDetail) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DoctorDetail) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *DoctorDetail) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *DoctorDetail) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *DoctorDetail) GetSpecialization() string {
	if x != nil {
		return x.Specialization
	}
	return ""
}

func (x *DoctorDetail) GetYearsOfExperience() int32 {
	if x != nil {
		return x.YearsOfExperience
	}
	return 0
}

func (x *DoctorDetail) GetLicenseNumber() string {
	if x != nil {
		return x.LicenseNumber
	}
	return ""
}

func (x *DoctorDetail) GetFees() int64 {
	if x != nil {
		return x.Fees
	}
	return 0
}

type DoctorSignUpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DoctorDetail *DoctorDetail `protobuf:"bytes,1,opt,name=DoctorDetail,proto3" json:"DoctorDetail,omitempty"`
	AccessToken  string        `protobuf:"bytes,2,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	RefreshToken string        `protobuf:"bytes,3,opt,name=RefreshToken,proto3" json:"RefreshToken,omitempty"`
}

func (x *DoctorSignUpResponse) Reset() {
	*x = DoctorSignUpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_doctor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoctorSignUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorSignUpResponse) ProtoMessage() {}

func (x *DoctorSignUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_doctor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorSignUpResponse.ProtoReflect.Descriptor instead.
func (*DoctorSignUpResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_doctor_proto_rawDescGZIP(), []int{2}
}

func (x *DoctorSignUpResponse) GetDoctorDetail() *DoctorDetail {
	if x != nil {
		return x.DoctorDetail
	}
	return nil
}

func (x *DoctorSignUpResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *DoctorSignUpResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type DoctorLoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *DoctorLoginRequest) Reset() {
	*x = DoctorLoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_doctor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoctorLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorLoginRequest) ProtoMessage() {}

func (x *DoctorLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_doctor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorLoginRequest.ProtoReflect.Descriptor instead.
func (*DoctorLoginRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_doctor_proto_rawDescGZIP(), []int{3}
}

func (x *DoctorLoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *DoctorLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type DoctorLoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DoctorDetail *DoctorDetail `protobuf:"bytes,1,opt,name=DoctorDetail,proto3" json:"DoctorDetail,omitempty"`
	AccessToken  string        `protobuf:"bytes,2,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	RefreshToken string        `protobuf:"bytes,3,opt,name=RefreshToken,proto3" json:"RefreshToken,omitempty"`
}

func (x *DoctorLoginResponse) Reset() {
	*x = DoctorLoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_doctor_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoctorLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorLoginResponse) ProtoMessage() {}

func (x *DoctorLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_doctor_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorLoginResponse.ProtoReflect.Descriptor instead.
func (*DoctorLoginResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_doctor_proto_rawDescGZIP(), []int{4}
}

func (x *DoctorLoginResponse) GetDoctorDetail() *DoctorDetail {
	if x != nil {
		return x.DoctorDetail
	}
	return nil
}

func (x *DoctorLoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *DoctorLoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type Doreq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Doreq) Reset() {
	*x = Doreq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_doctor_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Doreq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Doreq) ProtoMessage() {}

func (x *Doreq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_doctor_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Doreq.ProtoReflect.Descriptor instead.
func (*Doreq) Descriptor() ([]byte, []int) {
	return file_pkg_pb_doctor_proto_rawDescGZIP(), []int{5}
}

type DoId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DoId) Reset() {
	*x = DoId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_doctor_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoId) ProtoMessage() {}

func (x *DoId) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_doctor_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoId.ProtoReflect.Descriptor instead.
func (*DoId) Descriptor() ([]byte, []int) {
	return file_pkg_pb_doctor_proto_rawDescGZIP(), []int{6}
}

func (x *DoId) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DoctorsDetailr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName          string `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email             string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber       string `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Specialization    string `protobuf:"bytes,5,opt,name=specialization,proto3" json:"specialization,omitempty"`
	YearsOfExperience int32  `protobuf:"varint,6,opt,name=years_of_experience,json=yearsOfExperience,proto3" json:"years_of_experience,omitempty"`
	LicenseNumber     string `protobuf:"bytes,7,opt,name=license_number,json=licenseNumber,proto3" json:"license_number,omitempty"`
	Fees              int64  `protobuf:"varint,8,opt,name=fees,proto3" json:"fees,omitempty"`
	Rating            int32  `protobuf:"varint,9,opt,name=Rating,proto3" json:"Rating,omitempty"`
}

func (x *DoctorsDetailr) Reset() {
	*x = DoctorsDetailr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_doctor_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoctorsDetailr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorsDetailr) ProtoMessage() {}

func (x *DoctorsDetailr) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_doctor_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorsDetailr.ProtoReflect.Descriptor instead.
func (*DoctorsDetailr) Descriptor() ([]byte, []int) {
	return file_pkg_pb_doctor_proto_rawDescGZIP(), []int{7}
}

func (x *DoctorsDetailr) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DoctorsDetailr) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *DoctorsDetailr) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *DoctorsDetailr) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *DoctorsDetailr) GetSpecialization() string {
	if x != nil {
		return x.Specialization
	}
	return ""
}

func (x *DoctorsDetailr) GetYearsOfExperience() int32 {
	if x != nil {
		return x.YearsOfExperience
	}
	return 0
}

func (x *DoctorsDetailr) GetLicenseNumber() string {
	if x != nil {
		return x.LicenseNumber
	}
	return ""
}

func (x *DoctorsDetailr) GetFees() int64 {
	if x != nil {
		return x.Fees
	}
	return 0
}

func (x *DoctorsDetailr) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type DoctorsDetailre struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DoctorsDetailr []*DoctorsDetailr `protobuf:"bytes,1,rep,name=DoctorsDetailr,proto3" json:"DoctorsDetailr,omitempty"`
}

func (x *DoctorsDetailre) Reset() {
	*x = DoctorsDetailre{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_doctor_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoctorsDetailre) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorsDetailre) ProtoMessage() {}

func (x *DoctorsDetailre) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_doctor_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorsDetailre.ProtoReflect.Descriptor instead.
func (*DoctorsDetailre) Descriptor() ([]byte, []int) {
	return file_pkg_pb_doctor_proto_rawDescGZIP(), []int{8}
}

func (x *DoctorsDetailre) GetDoctorsDetailr() []*DoctorsDetailr {
	if x != nil {
		return x.DoctorsDetailr
	}
	return nil
}

type Doid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DoctorId string `protobuf:"bytes,1,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
}

func (x *Doid) Reset() {
	*x = Doid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_doctor_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Doid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Doid) ProtoMessage() {}

func (x *Doid) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_doctor_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Doid.ProtoReflect.Descriptor instead.
func (*Doid) Descriptor() ([]byte, []int) {
	return file_pkg_pb_doctor_proto_rawDescGZIP(), []int{9}
}

func (x *Doid) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

type Rate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rate uint32 `protobuf:"varint,1,opt,name=Rate,proto3" json:"Rate,omitempty"`
}

func (x *Rate) Reset() {
	*x = Rate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_doctor_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rate) ProtoMessage() {}

func (x *Rate) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_doctor_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rate.ProtoReflect.Descriptor instead.
func (*Rate) Descriptor() ([]byte, []int) {
	return file_pkg_pb_doctor_proto_rawDescGZIP(), []int{10}
}

func (x *Rate) GetRate() uint32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type RateDoctorReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Patientid string `protobuf:"bytes,1,opt,name=Patientid,proto3" json:"Patientid,omitempty"`
	DoctorId  string `protobuf:"bytes,2,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	Rate      *Rate  `protobuf:"bytes,3,opt,name=Rate,proto3" json:"Rate,omitempty"`
}

func (x *RateDoctorReq) Reset() {
	*x = RateDoctorReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_doctor_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RateDoctorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateDoctorReq) ProtoMessage() {}

func (x *RateDoctorReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_doctor_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateDoctorReq.ProtoReflect.Descriptor instead.
func (*RateDoctorReq) Descriptor() ([]byte, []int) {
	return file_pkg_pb_doctor_proto_rawDescGZIP(), []int{11}
}

func (x *RateDoctorReq) GetPatientid() string {
	if x != nil {
		return x.Patientid
	}
	return ""
}

func (x *RateDoctorReq) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

func (x *RateDoctorReq) GetRate() *Rate {
	if x != nil {
		return x.Rate
	}
	return nil
}

type UpdateDoctor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FullName          string `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email             string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber       string `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Specialization    string `protobuf:"bytes,4,opt,name=specialization,proto3" json:"specialization,omitempty"`
	YearsOfExperience int32  `protobuf:"varint,5,opt,name=years_of_experience,json=yearsOfExperience,proto3" json:"years_of_experience,omitempty"`
	Fees              int64  `protobuf:"varint,6,opt,name=fees,proto3" json:"fees,omitempty"`
}

func (x *UpdateDoctor) Reset() {
	*x = UpdateDoctor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_doctor_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDoctor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDoctor) ProtoMessage() {}

func (x *UpdateDoctor) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_doctor_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDoctor.ProtoReflect.Descriptor instead.
func (*UpdateDoctor) Descriptor() ([]byte, []int) {
	return file_pkg_pb_doctor_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateDoctor) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UpdateDoctor) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateDoctor) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UpdateDoctor) GetSpecialization() string {
	if x != nil {
		return x.Specialization
	}
	return ""
}

func (x *UpdateDoctor) GetYearsOfExperience() int32 {
	if x != nil {
		return x.YearsOfExperience
	}
	return 0
}

func (x *UpdateDoctor) GetFees() int64 {
	if x != nil {
		return x.Fees
	}
	return 0
}

type UpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Body *UpdateDoctor `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *UpdateReq) Reset() {
	*x = UpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_doctor_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReq) ProtoMessage() {}

func (x *UpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_doctor_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReq.ProtoReflect.Descriptor instead.
func (*UpdateReq) Descriptor() ([]byte, []int) {
	return file_pkg_pb_doctor_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateReq) GetBody() *UpdateDoctor {
	if x != nil {
		return x.Body
	}
	return nil
}

type Doctorreq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DoctorId int32 `protobuf:"varint,1,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
}

func (x *Doctorreq) Reset() {
	*x = Doctorreq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_doctor_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Doctorreq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Doctorreq) ProtoMessage() {}

func (x *Doctorreq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_doctor_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Doctorreq.ProtoReflect.Descriptor instead.
func (*Doctorreq) Descriptor() ([]byte, []int) {
	return file_pkg_pb_doctor_proto_rawDescGZIP(), []int{14}
}

func (x *Doctorreq) GetDoctorId() int32 {
	if x != nil {
		return x.DoctorId
	}
	return 0
}

type Doctorres struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bool bool `protobuf:"varint,1,opt,name=bool,proto3" json:"bool,omitempty"`
}

func (x *Doctorres) Reset() {
	*x = Doctorres{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_doctor_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Doctorres) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Doctorres) ProtoMessage() {}

func (x *Doctorres) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_doctor_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Doctorres.ProtoReflect.Descriptor instead.
func (*Doctorres) Descriptor() ([]byte, []int) {
	return file_pkg_pb_doctor_proto_rawDescGZIP(), []int{15}
}

func (x *Doctorres) GetBool() bool {
	if x != nil {
		return x.Bool
	}
	return false
}

type Bookingres struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DoctorId    int32  `protobuf:"varint,1,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	DoctorName  string `protobuf:"bytes,2,opt,name=doctor_name,json=doctorName,proto3" json:"doctor_name,omitempty"`
	DoctorEmail string `protobuf:"bytes,3,opt,name=doctor_email,json=doctorEmail,proto3" json:"doctor_email,omitempty"`
	Fees        int64  `protobuf:"varint,4,opt,name=fees,proto3" json:"fees,omitempty"`
}

func (x *Bookingres) Reset() {
	*x = Bookingres{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_doctor_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bookingres) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bookingres) ProtoMessage() {}

func (x *Bookingres) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_doctor_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bookingres.ProtoReflect.Descriptor instead.
func (*Bookingres) Descriptor() ([]byte, []int) {
	return file_pkg_pb_doctor_proto_rawDescGZIP(), []int{16}
}

func (x *Bookingres) GetDoctorId() int32 {
	if x != nil {
		return x.DoctorId
	}
	return 0
}

func (x *Bookingres) GetDoctorName() string {
	if x != nil {
		return x.DoctorName
	}
	return ""
}

func (x *Bookingres) GetDoctorEmail() string {
	if x != nil {
		return x.DoctorEmail
	}
	return ""
}

func (x *Bookingres) GetFees() int64 {
	if x != nil {
		return x.Fees
	}
	return 0
}

var File_pkg_pb_doctor_proto protoreflect.FileDescriptor

var file_pkg_pb_doctor_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x22, 0xc5, 0x02,
	0x0a, 0x13, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x6e,
	0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x72, 0x6d, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x73, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x70, 0x65, 0x63,
	0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x13, 0x79, 0x65,
	0x61, 0x72, 0x73, 0x5f, 0x6f, 0x66, 0x5f, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x79, 0x65, 0x61, 0x72, 0x73, 0x4f, 0x66,
	0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x6c, 0x69,
	0x63, 0x65, 0x6e, 0x73, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x65, 0x65, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x66, 0x65, 0x65, 0x73, 0x22, 0x87, 0x02, 0x0a, 0x0c, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x68, 0x6f,
	0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x26, 0x0a, 0x0e,
	0x73, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x13, 0x79, 0x65, 0x61, 0x72, 0x73, 0x5f, 0x6f, 0x66,
	0x5f, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x11, 0x79, 0x65, 0x61, 0x72, 0x73, 0x4f, 0x66, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69,
	0x65, 0x6e, 0x63, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x5f,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6c, 0x69,
	0x63, 0x65, 0x6e, 0x73, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x66,
	0x65, 0x65, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x66, 0x65, 0x65, 0x73, 0x22,
	0x96, 0x01, 0x0a, 0x14, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x0c, 0x44, 0x6f, 0x63, 0x74,
	0x6f, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x52, 0x0c, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x52, 0x65, 0x66, 0x72,
	0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x46, 0x0a, 0x12, 0x44, 0x6f, 0x63, 0x74,
	0x6f, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x22, 0x95, 0x01, 0x0a, 0x13, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x0c, 0x44, 0x6f, 0x63, 0x74,
	0x6f, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x52, 0x0c, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x52, 0x65, 0x66, 0x72,
	0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x07, 0x0a, 0x05, 0x44, 0x6f, 0x72, 0x65,
	0x71, 0x22, 0x17, 0x0a, 0x05, 0x44, 0x6f, 0x5f, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0xa1, 0x02, 0x0a, 0x0e, 0x44,
	0x6f, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x72, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x12, 0x21, 0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x26, 0x0a, 0x0e, 0x73, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x7a,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x70, 0x65,
	0x63, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x13, 0x79,
	0x65, 0x61, 0x72, 0x73, 0x5f, 0x6f, 0x66, 0x5f, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e,
	0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x79, 0x65, 0x61, 0x72, 0x73, 0x4f,
	0x66, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x6c,
	0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x65, 0x65, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x66, 0x65, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x51,
	0x0a, 0x0f, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x72,
	0x65, 0x12, 0x3e, 0x0a, 0x0e, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x64, 0x6f, 0x63, 0x74,
	0x6f, 0x72, 0x2e, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x72, 0x52, 0x0e, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x72, 0x22, 0x23, 0x0a, 0x04, 0x44, 0x6f, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x6f, 0x63,
	0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x6f,
	0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x22, 0x1a, 0x0a, 0x04, 0x52, 0x61, 0x74, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x52, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x52, 0x61,
	0x74, 0x65, 0x22, 0x6c, 0x0a, 0x0d, 0x52, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72,
	0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x69,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x20,
	0x0a, 0x04, 0x52, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x64,
	0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x52, 0x04, 0x52, 0x61, 0x74, 0x65,
	0x22, 0xd0, 0x01, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x63, 0x74, 0x6f,
	0x72, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e,
	0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x26, 0x0a, 0x0e, 0x73, 0x70, 0x65, 0x63, 0x69,
	0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x73, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x2e, 0x0a, 0x13, 0x79, 0x65, 0x61, 0x72, 0x73, 0x5f, 0x6f, 0x66, 0x5f, 0x65, 0x78, 0x70, 0x65,
	0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x79, 0x65,
	0x61, 0x72, 0x73, 0x4f, 0x66, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x66, 0x65, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x66,
	0x65, 0x65, 0x73, 0x22, 0x45, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x28, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x6f,
	0x63, 0x74, 0x6f, 0x72, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x28, 0x0a, 0x09, 0x64, 0x6f,
	0x63, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x6f, 0x63, 0x74, 0x6f,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x6f, 0x63, 0x74,
	0x6f, 0x72, 0x49, 0x64, 0x22, 0x1f, 0x0a, 0x09, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x72, 0x65,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x22, 0x81, 0x01, 0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e,
	0x67, 0x72, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x49,
	0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x65, 0x65, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x66, 0x65, 0x65, 0x73, 0x32, 0xc1, 0x04, 0x0a, 0x06, 0x44, 0x6f,
	0x63, 0x74, 0x6f, 0x72, 0x12, 0x4b, 0x0a, 0x0c, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x69,
	0x67, 0x6e, 0x55, 0x70, 0x12, 0x1b, 0x2e, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x6f,
	0x63, 0x74, 0x6f, 0x72, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x6f, 0x63, 0x74, 0x6f,
	0x72, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x48, 0x0a, 0x0b, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x12, 0x1a, 0x2e, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x64,
	0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x0d, 0x44,
	0x6f, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x0d, 0x2e, 0x64,
	0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x6f, 0x72, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x64, 0x6f,
	0x63, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x72, 0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x10, 0x49, 0x6e, 0x64, 0x69, 0x76, 0x69,
	0x64, 0x75, 0x61, 0x6c, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x0c, 0x2e, 0x64, 0x6f, 0x63,
	0x74, 0x6f, 0x72, 0x2e, 0x44, 0x6f, 0x69, 0x64, 0x1a, 0x16, 0x2e, 0x64, 0x6f, 0x63, 0x74, 0x6f,
	0x72, 0x2e, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x72,
	0x22, 0x00, 0x12, 0x38, 0x0a, 0x0d, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x12, 0x0d, 0x2e, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x6f, 0x5f,
	0x69, 0x64, 0x1a, 0x16, 0x2e, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x6f, 0x63, 0x74,
	0x6f, 0x72, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x72, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x0a,
	0x52, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x15, 0x2e, 0x64, 0x6f, 0x63,
	0x74, 0x6f, 0x72, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65,
	0x71, 0x1a, 0x0c, 0x2e, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x22,
	0x00, 0x12, 0x40, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x63, 0x74, 0x6f,
	0x72, 0x50, 0x72, 0x6f, 0x69, 0x66, 0x6c, 0x65, 0x12, 0x11, 0x2e, 0x64, 0x6f, 0x63, 0x74, 0x6f,
	0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x64, 0x6f,
	0x63, 0x74, 0x6f, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x63, 0x74, 0x6f,
	0x72, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x0b, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x64, 0x6f, 0x63, 0x74,
	0x6f, 0x72, 0x12, 0x11, 0x2e, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x64, 0x6f, 0x63, 0x74,
	0x6f, 0x72, 0x72, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x64,
	0x6f, 0x63, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x73, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x16, 0x44, 0x6f,
	0x63, 0x74, 0x6f, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x66, 0x6f, 0x72, 0x42, 0x6f, 0x6f,
	0x6b, 0x69, 0x6e, 0x67, 0x12, 0x11, 0x2e, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x64, 0x6f,
	0x63, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72,
	0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x22, 0x00, 0x42, 0x0a, 0x5a,
	0x08, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_pkg_pb_doctor_proto_rawDescOnce sync.Once
	file_pkg_pb_doctor_proto_rawDescData = file_pkg_pb_doctor_proto_rawDesc
)

func file_pkg_pb_doctor_proto_rawDescGZIP() []byte {
	file_pkg_pb_doctor_proto_rawDescOnce.Do(func() {
		file_pkg_pb_doctor_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_pb_doctor_proto_rawDescData)
	})
	return file_pkg_pb_doctor_proto_rawDescData
}

var file_pkg_pb_doctor_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_pkg_pb_doctor_proto_goTypes = []interface{}{
	(*DoctorSignUpRequest)(nil),  // 0: doctor.DoctorSignUpRequest
	(*DoctorDetail)(nil),         // 1: doctor.DoctorDetail
	(*DoctorSignUpResponse)(nil), // 2: doctor.DoctorSignUpResponse
	(*DoctorLoginRequest)(nil),   // 3: doctor.DoctorLoginRequest
	(*DoctorLoginResponse)(nil),  // 4: doctor.DoctorLoginResponse
	(*Doreq)(nil),                // 5: doctor.Doreq
	(*DoId)(nil),                 // 6: doctor.Do_id
	(*DoctorsDetailr)(nil),       // 7: doctor.DoctorsDetailr
	(*DoctorsDetailre)(nil),      // 8: doctor.DoctorsDetailre
	(*Doid)(nil),                 // 9: doctor.Doid
	(*Rate)(nil),                 // 10: doctor.Rate
	(*RateDoctorReq)(nil),        // 11: doctor.RateDoctorReq
	(*UpdateDoctor)(nil),         // 12: doctor.UpdateDoctor
	(*UpdateReq)(nil),            // 13: doctor.UpdateReq
	(*Doctorreq)(nil),            // 14: doctor.doctorreq
	(*Doctorres)(nil),            // 15: doctor.doctorres
	(*Bookingres)(nil),           // 16: doctor.bookingres
}
var file_pkg_pb_doctor_proto_depIdxs = []int32{
	1,  // 0: doctor.DoctorSignUpResponse.DoctorDetail:type_name -> doctor.DoctorDetail
	1,  // 1: doctor.DoctorLoginResponse.DoctorDetail:type_name -> doctor.DoctorDetail
	7,  // 2: doctor.DoctorsDetailre.DoctorsDetailr:type_name -> doctor.DoctorsDetailr
	10, // 3: doctor.RateDoctorReq.Rate:type_name -> doctor.Rate
	12, // 4: doctor.UpdateReq.body:type_name -> doctor.UpdateDoctor
	0,  // 5: doctor.Doctor.DoctorSignUp:input_type -> doctor.DoctorSignUpRequest
	3,  // 6: doctor.Doctor.DoctorLogin:input_type -> doctor.DoctorLoginRequest
	5,  // 7: doctor.Doctor.DoctorsDetail:input_type -> doctor.Doreq
	9,  // 8: doctor.Doctor.IndividualDoctor:input_type -> doctor.Doid
	6,  // 9: doctor.Doctor.DoctorProfile:input_type -> doctor.Do_id
	11, // 10: doctor.Doctor.RateDoctor:input_type -> doctor.RateDoctorReq
	13, // 11: doctor.Doctor.UpdateDoctorProifle:input_type -> doctor.UpdateReq
	14, // 12: doctor.Doctor.Checkdoctor:input_type -> doctor.doctorreq
	14, // 13: doctor.Doctor.DoctorDetailforBooking:input_type -> doctor.doctorreq
	2,  // 14: doctor.Doctor.DoctorSignUp:output_type -> doctor.DoctorSignUpResponse
	4,  // 15: doctor.Doctor.DoctorLogin:output_type -> doctor.DoctorLoginResponse
	8,  // 16: doctor.Doctor.DoctorsDetail:output_type -> doctor.DoctorsDetailre
	7,  // 17: doctor.Doctor.IndividualDoctor:output_type -> doctor.DoctorsDetailr
	7,  // 18: doctor.Doctor.DoctorProfile:output_type -> doctor.DoctorsDetailr
	10, // 19: doctor.Doctor.RateDoctor:output_type -> doctor.Rate
	12, // 20: doctor.Doctor.UpdateDoctorProifle:output_type -> doctor.UpdateDoctor
	15, // 21: doctor.Doctor.Checkdoctor:output_type -> doctor.doctorres
	16, // 22: doctor.Doctor.DoctorDetailforBooking:output_type -> doctor.bookingres
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_pb_doctor_proto_init() }
func file_pkg_pb_doctor_proto_init() {
	if File_pkg_pb_doctor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_pb_doctor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoctorSignUpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_doctor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoctorDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_doctor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoctorSignUpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_doctor_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoctorLoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_doctor_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoctorLoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_doctor_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Doreq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_doctor_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_doctor_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoctorsDetailr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_doctor_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoctorsDetailre); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_doctor_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Doid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_doctor_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_doctor_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RateDoctorReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_doctor_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDoctor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_doctor_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_doctor_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Doctorreq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_doctor_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Doctorres); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_doctor_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bookingres); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_pb_doctor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_doctor_proto_goTypes,
		DependencyIndexes: file_pkg_pb_doctor_proto_depIdxs,
		MessageInfos:      file_pkg_pb_doctor_proto_msgTypes,
	}.Build()
	File_pkg_pb_doctor_proto = out.File
	file_pkg_pb_doctor_proto_rawDesc = nil
	file_pkg_pb_doctor_proto_goTypes = nil
	file_pkg_pb_doctor_proto_depIdxs = nil
}
