// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: pkg/pb/doctor/doctor.proto

package doctor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Doctorreq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DoctorId int32 `protobuf:"varint,1,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
}

func (x *Doctorreq) Reset() {
	*x = Doctorreq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_doctor_doctor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Doctorreq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Doctorreq) ProtoMessage() {}

func (x *Doctorreq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_doctor_doctor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Doctorreq.ProtoReflect.Descriptor instead.
func (*Doctorreq) Descriptor() ([]byte, []int) {
	return file_pkg_pb_doctor_doctor_proto_rawDescGZIP(), []int{0}
}

func (x *Doctorreq) GetDoctorId() int32 {
	if x != nil {
		return x.DoctorId
	}
	return 0
}

type Doctorres struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bool  bool   `protobuf:"varint,1,opt,name=bool,proto3" json:"bool,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (x *Doctorres) Reset() {
	*x = Doctorres{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_doctor_doctor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Doctorres) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Doctorres) ProtoMessage() {}

func (x *Doctorres) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_doctor_doctor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Doctorres.ProtoReflect.Descriptor instead.
func (*Doctorres) Descriptor() ([]byte, []int) {
	return file_pkg_pb_doctor_doctor_proto_rawDescGZIP(), []int{1}
}

func (x *Doctorres) GetBool() bool {
	if x != nil {
		return x.Bool
	}
	return false
}

func (x *Doctorres) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Bookingres struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DoctorId    int32  `protobuf:"varint,1,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	DoctorName  string `protobuf:"bytes,2,opt,name=doctor_name,json=doctorName,proto3" json:"doctor_name,omitempty"`
	DoctorEmail string `protobuf:"bytes,3,opt,name=doctor_email,json=doctorEmail,proto3" json:"doctor_email,omitempty"`
	Fees        int64  `protobuf:"varint,4,opt,name=fees,proto3" json:"fees,omitempty"`
}

func (x *Bookingres) Reset() {
	*x = Bookingres{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_doctor_doctor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bookingres) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bookingres) ProtoMessage() {}

func (x *Bookingres) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_doctor_doctor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bookingres.ProtoReflect.Descriptor instead.
func (*Bookingres) Descriptor() ([]byte, []int) {
	return file_pkg_pb_doctor_doctor_proto_rawDescGZIP(), []int{2}
}

func (x *Bookingres) GetDoctorId() int32 {
	if x != nil {
		return x.DoctorId
	}
	return 0
}

func (x *Bookingres) GetDoctorName() string {
	if x != nil {
		return x.DoctorName
	}
	return ""
}

func (x *Bookingres) GetDoctorEmail() string {
	if x != nil {
		return x.DoctorEmail
	}
	return ""
}

func (x *Bookingres) GetFees() int64 {
	if x != nil {
		return x.Fees
	}
	return 0
}

var File_pkg_pb_doctor_doctor_proto protoreflect.FileDescriptor

var file_pkg_pb_doctor_doctor_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2f,
	0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x64, 0x6f,
	0x63, 0x74, 0x6f, 0x72, 0x22, 0x28, 0x0a, 0x09, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x72, 0x65,
	0x71, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x22, 0x35,
	0x0a, 0x09, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x62,
	0x6f, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x12,
	0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x81, 0x01, 0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e,
	0x67, 0x72, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x49,
	0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x65, 0x65, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x66, 0x65, 0x65, 0x73, 0x32, 0x82, 0x01, 0x0a, 0x06, 0x44, 0x6f,
	0x63, 0x74, 0x6f, 0x72, 0x12, 0x35, 0x0a, 0x0b, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x64, 0x6f, 0x63,
	0x74, 0x6f, 0x72, 0x12, 0x11, 0x2e, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x64, 0x6f, 0x63,
	0x74, 0x6f, 0x72, 0x72, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e,
	0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x73, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x16, 0x44,
	0x6f, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x66, 0x6f, 0x72, 0x42, 0x6f,
	0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x11, 0x2e, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x64,
	0x6f, 0x63, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x64, 0x6f, 0x63, 0x74, 0x6f,
	0x72, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x22, 0x00, 0x42, 0x11,
	0x5a, 0x0f, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x64, 0x6f, 0x63, 0x74, 0x6f,
	0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_pb_doctor_doctor_proto_rawDescOnce sync.Once
	file_pkg_pb_doctor_doctor_proto_rawDescData = file_pkg_pb_doctor_doctor_proto_rawDesc
)

func file_pkg_pb_doctor_doctor_proto_rawDescGZIP() []byte {
	file_pkg_pb_doctor_doctor_proto_rawDescOnce.Do(func() {
		file_pkg_pb_doctor_doctor_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_pb_doctor_doctor_proto_rawDescData)
	})
	return file_pkg_pb_doctor_doctor_proto_rawDescData
}

var file_pkg_pb_doctor_doctor_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_pb_doctor_doctor_proto_goTypes = []interface{}{
	(*Doctorreq)(nil),  // 0: doctor.doctorreq
	(*Doctorres)(nil),  // 1: doctor.doctorres
	(*Bookingres)(nil), // 2: doctor.bookingres
}
var file_pkg_pb_doctor_doctor_proto_depIdxs = []int32{
	0, // 0: doctor.Doctor.Checkdoctor:input_type -> doctor.doctorreq
	0, // 1: doctor.Doctor.DoctorDetailforBooking:input_type -> doctor.doctorreq
	1, // 2: doctor.Doctor.Checkdoctor:output_type -> doctor.doctorres
	2, // 3: doctor.Doctor.DoctorDetailforBooking:output_type -> doctor.bookingres
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_pb_doctor_doctor_proto_init() }
func file_pkg_pb_doctor_doctor_proto_init() {
	if File_pkg_pb_doctor_doctor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_pb_doctor_doctor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Doctorreq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_doctor_doctor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Doctorres); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_doctor_doctor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bookingres); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_pb_doctor_doctor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_doctor_doctor_proto_goTypes,
		DependencyIndexes: file_pkg_pb_doctor_doctor_proto_depIdxs,
		MessageInfos:      file_pkg_pb_doctor_doctor_proto_msgTypes,
	}.Build()
	File_pkg_pb_doctor_doctor_proto = out.File
	file_pkg_pb_doctor_doctor_proto_rawDesc = nil
	file_pkg_pb_doctor_doctor_proto_goTypes = nil
	file_pkg_pb_doctor_doctor_proto_depIdxs = nil
}
