// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: pkg/pb/patient/patient.proto

package patient

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Patient_GoogleSignIn_FullMethodName         = "/patient.Patient/GoogleSignIn"
	Patient_IndPatientDetails_FullMethodName    = "/patient.Patient/IndPatientDetails"
	Patient_UpdatePatientDetails_FullMethodName = "/patient.Patient/UpdatePatientDetails"
	Patient_ListPatients_FullMethodName         = "/patient.Patient/ListPatients"
)

// PatientClient is the client API for Patient service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PatientClient interface {
	GoogleSignIn(ctx context.Context, in *GoogleSignInRequest, opts ...grpc.CallOption) (*PatientSignUpResponse, error)
	IndPatientDetails(ctx context.Context, in *Idreq, opts ...grpc.CallOption) (*PatientDetails, error)
	UpdatePatientDetails(ctx context.Context, in *PatientDetails, opts ...grpc.CallOption) (*PatientDetails, error)
	ListPatients(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Listpares, error)
}

type patientClient struct {
	cc grpc.ClientConnInterface
}

func NewPatientClient(cc grpc.ClientConnInterface) PatientClient {
	return &patientClient{cc}
}

func (c *patientClient) GoogleSignIn(ctx context.Context, in *GoogleSignInRequest, opts ...grpc.CallOption) (*PatientSignUpResponse, error) {
	out := new(PatientSignUpResponse)
	err := c.cc.Invoke(ctx, Patient_GoogleSignIn_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patientClient) IndPatientDetails(ctx context.Context, in *Idreq, opts ...grpc.CallOption) (*PatientDetails, error) {
	out := new(PatientDetails)
	err := c.cc.Invoke(ctx, Patient_IndPatientDetails_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patientClient) UpdatePatientDetails(ctx context.Context, in *PatientDetails, opts ...grpc.CallOption) (*PatientDetails, error) {
	out := new(PatientDetails)
	err := c.cc.Invoke(ctx, Patient_UpdatePatientDetails_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patientClient) ListPatients(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Listpares, error) {
	out := new(Listpares)
	err := c.cc.Invoke(ctx, Patient_ListPatients_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PatientServer is the server API for Patient service.
// All implementations must embed UnimplementedPatientServer
// for forward compatibility
type PatientServer interface {
	GoogleSignIn(context.Context, *GoogleSignInRequest) (*PatientSignUpResponse, error)
	IndPatientDetails(context.Context, *Idreq) (*PatientDetails, error)
	UpdatePatientDetails(context.Context, *PatientDetails) (*PatientDetails, error)
	ListPatients(context.Context, *Req) (*Listpares, error)
	mustEmbedUnimplementedPatientServer()
}

// UnimplementedPatientServer must be embedded to have forward compatible implementations.
type UnimplementedPatientServer struct {
}

func (UnimplementedPatientServer) GoogleSignIn(context.Context, *GoogleSignInRequest) (*PatientSignUpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GoogleSignIn not implemented")
}
func (UnimplementedPatientServer) IndPatientDetails(context.Context, *Idreq) (*PatientDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IndPatientDetails not implemented")
}
func (UnimplementedPatientServer) UpdatePatientDetails(context.Context, *PatientDetails) (*PatientDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePatientDetails not implemented")
}
func (UnimplementedPatientServer) ListPatients(context.Context, *Req) (*Listpares, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPatients not implemented")
}
func (UnimplementedPatientServer) mustEmbedUnimplementedPatientServer() {}

// UnsafePatientServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PatientServer will
// result in compilation errors.
type UnsafePatientServer interface {
	mustEmbedUnimplementedPatientServer()
}

func RegisterPatientServer(s grpc.ServiceRegistrar, srv PatientServer) {
	s.RegisterService(&Patient_ServiceDesc, srv)
}

func _Patient_GoogleSignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoogleSignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatientServer).GoogleSignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Patient_GoogleSignIn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatientServer).GoogleSignIn(ctx, req.(*GoogleSignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Patient_IndPatientDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Idreq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatientServer).IndPatientDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Patient_IndPatientDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatientServer).IndPatientDetails(ctx, req.(*Idreq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Patient_UpdatePatientDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatientDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatientServer).UpdatePatientDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Patient_UpdatePatientDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatientServer).UpdatePatientDetails(ctx, req.(*PatientDetails))
	}
	return interceptor(ctx, in, info, handler)
}

func _Patient_ListPatients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatientServer).ListPatients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Patient_ListPatients_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatientServer).ListPatients(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

// Patient_ServiceDesc is the grpc.ServiceDesc for Patient service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Patient_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "patient.Patient",
	HandlerType: (*PatientServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GoogleSignIn",
			Handler:    _Patient_GoogleSignIn_Handler,
		},
		{
			MethodName: "IndPatientDetails",
			Handler:    _Patient_IndPatientDetails_Handler,
		},
		{
			MethodName: "UpdatePatientDetails",
			Handler:    _Patient_UpdatePatientDetails_Handler,
		},
		{
			MethodName: "ListPatients",
			Handler:    _Patient_ListPatients_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/pb/patient/patient.proto",
}
